### PR TITLE
Trio is now typed, no need for trio-typing

### PR DESCRIPTION
**Pull request by mikenerone**
trio-typing is generally a bit broken and causes type-checking troubles for users (e.g. me) when pulled in by tricycle. Also updated the support Python versions (3.7 EOL, long live 3.12).

### CODE REVIEW

**Comment by mikenerone** [comment]
There are currently some typing warnings on a bunch of the `start_soon()` calls in the tests, but I'm failing to spot why the "expected" signature is so strict (accepting only a single positional arg?). I might just be tired. :P

**Comment by graingert** [comment]
@mikenerone fixed by upgrading mypy https://github.com/oremanj/tricycle/pull/25

**Comment by mikenerone** [comment]
@graingert Thanks! I was totally missing it being a mypy bug. I've pulled your commits into this PR.

**Comment by oremanj** [comment]
macOS is still building on 3.7 which now fails. 3.13-dev seems broken, you can remove it from the matrix.

**Pull request merged**
